Set Shell zsh
Sleep 500ms
Type "revq --help"
Sleep 500ms
Enter
Sleep 500ms
Type "r"
Sleep 500ms
Type "evq"
Enter
Sleep 4.5s
Escape
Sleep 500ms
Type "revq "
Sleep 500ms
Type "-u dani"
Sleep 500ms
Type "elr"
Sleep 500ms
Type "oe"
Sleep 500ms
Enter
Sleep 11s
Escape
Sleep 500ms
Type "revq --org"
Enter
Sleep 3s
Escape
Sleep 1s
Type "revq --org --all"
Enter
Sleep 4s
Escape
Sleep 500ms
Type "revq --"
Sleep 500ms
Type "req"
Enter
Sleep 5s
Escape
Sleep 1s
Ctrl+D

